### ISSUE TITLE
JWT encoded facebook profile

### ISSUE THREAD

**Issue by Howard-Zhou** [Cyann-UBC/Cyann#10]
So I was trying out the JWT implementation and when I tried to console.log(req.users) which is added by express-jwt middleware, I got my facebook profile back.
<img width="526" alt="screen shot 2016-11-14 at 9 15 14 pm" src="https://cloud.githubusercontent.com/assets/15649136/20294096/7f6facb2-aab0-11e6-85cd-95f92f473b8b.png">
Should we encode the JWT with a newly created Cyann user profile so we can get Cyann users in req.users?

**Comment by cs824655** [comment]
yes, we have encoded jwt this way. The only peoblem is that I did not assign the user id in our database to req.user. I will fix it later
