### ISSUE TITLE
Creating a course & creating folders on server for uploaded documents

### ISSUE THREAD

**Issue by tohjustin** [Cyann-UBC/Cyann#25]
If our server doesn't have an upload folder, creating course request doesn't get true.

@Howard-Zhou Not sure if you consider this a bug.

**Comment by Howard-Zhou** [comment]
I do. I tried pushing an empty uploads/ folder to master branch to no avail

**Comment by tohjustin** [comment]
ok, I did a work around by adding a README.md as a placeholder for the empty directory. Resolved on master branch commit #3fd4f77.
