### ISSUE TITLE
When populating, user's entire profile needed

### ISSUE THREAD

**Issue by Howard-Zhou** [Cyann-UBC/Cyann#27]
`.populate("instructor", "name", Users)`
`  .populate("posts.author", "name", Users)`
` .populate("posts.comments.author", "name", Users)`
Only getting user's name in response object, profileImage's URL and email address also needed

**Comment by luvianwang** [comment]
userType is also needed when populating

**Comment by tohjustin** [comment]
Fix pushed to master branch at commit #b2ec936
