### ISSUE TITLE
No access control implemented for API endpoints

### ISSUE THREAD

**Issue by tohjustin** [Cyann-UBC/Cyann#38]
**Description:**
Current any type of user can access all the API endpoints but we would like to restrict this. (eg. Only instructors & TAs can set answer, delete posts etc.)

**Expected Behaviour:**
Implement access control for certain **PUT** & **DELETE** endpoints (see https://docs.google.com/spreadsheets/d/1WjBdrm445uKsrXzDK-gf0szL8rBt-vJmPWbwBFrrzdw/edit?usp=sharing)

**Comment by cs824655** [comment]
All user access control has been implemented.
